// TODO
// ease-in
// ease-in-out

// lottie keyframe
const keyframes = (bottom?: string, right?: string) => [
  {
    bottom: '50%',
    right: '50%',
    width: '8px',
    height: '8px',
    borderTopLeftRadius: '100px',
    borderTopRightRadius: '100px',
    borderBottomLeftRadius: '100px',
    borderBottomRightRadius: '100px',
    opacity: '1',
  },
  {
    bottom: '50%',
    right: '50%',
    width: '250px',
    height: '250px',
    borderTopLeftRadius: '100px',
    borderTopRightRadius: '100px',
    borderBottomLeftRadius: '100px',
    borderBottomRightRadius: '100px',
    opacity: '1',
  },
  {
    bottom: '45px',
    right: '25%',
    width: '500px',
    height: '500px',
    borderTopLeftRadius: '500px',
    borderTopRightRadius: '500px',
    borderBottomLeftRadius: '500px',
    borderBottomRightRadius: '500px',
    transform: 'scale(50) translate3d(0,0,0)',
    opacity: '1',
  },
  {
    bottom: '45px',
    right: '25%',
    width: '500px',
    height: '500px',
    borderTopLeftRadius: '500px',
    borderTopRightRadius: '500px',
    borderBottomLeftRadius: '500px',
    borderBottomRightRadius: '500px',
    transform: 'scale(25) translate3d(0,0,0)',
    opacity: '1',
  },
  {
    bottom: '45px',
    right: '25%',
    width: '250px',
    height: '250px',
    borderTopLeftRadius: '1000px',
    borderTopRightRadius: '1000px',
    borderBottomLeftRadius: '1000px',
    borderBottomRightRadius: '1000px',
    transform: 'scale(15) translate3d(0,0,0)',
    opacity: '1',
  },
  {
    bottom,
    right,
    width: '60px',
    height: '60px',
    borderTopLeftRadius: '30px',
    borderTopRightRadius: '30px',
    borderBottomLeftRadius: '30px',
    borderBottomRightRadius: '30px',
    transform: 'scale(1) translate3d(0, 0, 0)',
    opacity: '1',
  },
  {
    bottom,
    right,
    width: '60px',
    height: '60px',
    borderTopLeftRadius: '30px',
    borderTopRightRadius: '30px',
    borderBottomLeftRadius: '30px',
    borderBottomRightRadius: '30px',
    transform: 'scale(1) translate3d(0, 0, 0)',
    opacity: '1',
  },
  {
    bottom,
    right,
    width: '60px',
    height: '60px',
    borderTopLeftRadius: '30px',
    borderTopRightRadius: '30px',
    borderBottomLeftRadius: '30px',
    borderBottomRightRadius: '30px',
    transform: 'scale(1) translate3d(0, 0, 0)',
    visibility: 'hidden',
    opacity: '0',
  },
  {
    bottom,
    right,
    width: '60px',
    height: '60px',
    borderTopLeftRadius: '30px',
    borderTopRightRadius: '30px',
    borderBottomLeftRadius: '30px',
    borderBottomRightRadius: '30px',
    transform: 'scale(1) translate3d(0, 0, 0)',
    visibility: 'hidden',
    opacity: '0',
    boxShadow: '0px 0px 10px rgba(26, 26, 26, 0.1)',
  },
];

// lottie keyframe options
const options = { duration: 2900, iterations: 1, fill: 'forwards' };

export { keyframes, options };
